// TOAST
export const SHOW_TOAST = "SHOW_TOAST"

// MODALS
export const LOGIN_MODAL = "LOGIN_MODAL";
export const REGISTER_MODAL = "REGISTER_MODAL";
export const FORGOT_MODAL = "FORGOT_MODAL";
export const RESET_PASSWORD_MODAL = "RESET_PASSWORD_MODAL";
export const BOOK_LOTTERY_MODAL = 'BOOK_LOTTERY_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const USERSETTINGS_MODAL = 'USERSETTINGS_MODAL'
export const CHANGE_PASSWORD_MODAL = 'CHANGE_PASSWORD_MODAL'
export const MY_BOOKINGS_LOTTERY_MODAL = 'MY_BOOKINGS_LOTTERY_MODAL'

//Auth Actions
export const LOGIN_RESPONSE = "LOGIN_RESPONSE"
export const REGISTER_RESPONSE = "REGISTER_RESPONSE"
export const SOCIAL_LOGIN_RESPONSE = "SOCIAL_LOGIN_RESPONSE"
export const FORGOT_RESPONSE = "FORGOT_RESPONSE"
export const RESET_PASSWORD_RESPONSE = "RESET_PASSWORD_RESPONSE"
export const VERIFY_OTP_RESPONSE = "VERIFY_OTP_RESPONSE"
export const VALIDATE_OTP_RESPONSE = "VALIDATE_OTP_RESPONSE"
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"
export const LOGOUT = "LOGOUT"
export const USER_DATA = "USER_DATA"
export const USER_TOKEN = "USER_TOKEN"
export const UPDATE_USER = "UPDATE_USER"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"


// portfolios
export const GET_MY_PORTFOLIOS = "GET_MY_PORTFOLIOS"
export const ADD_MY_PORTFOLIOS = "ADD_MY_PORTFOLIOS"
export const EDIT_MY_PORTFOLIOS = "EDIT_MY_PORTFOLIOS"
export const DELETE_MY_PORTFOLIOS = "DELETE_MY_PORTFOLIOS"

// Connection
export const MY_WALLET_RESPONSE = "MY_WALLET_RESPONSE"
export const MY_TOKENS_ON_ADDRESS = "MY_TOKENS_ON_ADDRESS"


// Common Action
export const CALL_RESPONSE = "CALL_RESPONSE"